### ISSUE TITLE
Testing running in Chrome under Linux

### ISSUE THREAD

**Issue by justinriddiough** [tijmenvangulik/Ergometerspace#21]
I have a raspberry device that runs chrome and after setting the beta features flag, was able to 'connect' to the rowing machine. However, I think that it wasn't communicating. I'm opening this ticket, as I will attempt this again to see if it maybe works. 

If it doesn't work - possibly we can debug a little bit to identify what the difference is in the browser API that communicates with USB/bluetooth devices between linux and windows.

In my setup, I have a small 12 touch screen monitor that has the raspberry pi mounted to the back of it, and so it would be nice to kind of make it a standalone setup for recording the rowing sessions

**Comment by tijmenvangulik** [comment]
Hi ,

I have never tried the linux or the pi (just only windows , mac os and android). I googled a bit on this subject. To get blue tooth working in chrome on linux there are some pre conditions:

https://acassis.wordpress.com/2016/06/28/how-to-get-chrome-web-bluetooth-working-on-linux/ <https://acassis.wordpress.com/2016/06/28/how-to-get-chrome-web-bluetooth-working-on-linux/>

It is possible for me to also do a electron / linux build. But this wil not fix any blue tooth issues because it uses the same chome web blue tooth stack as the browser.

You can also think about installing android on your raspberry pi. I think this may make it a lot easier for you. (And maybe also for the end users because android is good with touch screens ) I have supported android fro quite some time.You can download it from the google play store.

https://magpi.raspberrypi.org/articles/android-raspberry-pi <https://magpi.raspberrypi.org/articles/android-raspberry-pi>


Tijmen

**Comment by tijmenvangulik** [comment]
This is the chrome doc’s:

https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md <https://github.com/WebBluetoothCG/web-bluetooth/blob/master/implementation-status.md>

 Requires Kernel 3.19+ and BlueZ <http://www.bluez.org/> 5.41+ installed. Read How to get Chrome Web Bluetooth working on Linux <https://acassis.wordpress.com/2016/06/28/how-to-get-chrome-web-bluetooth-working-on-linux/>.
Note that Bluetooth daemon needs to run with experimental interfaces if BlueZ version is lower than 5.43: sudo /usr/sbin/bluetoothd -E

**Comment by justinriddiough** [comment]
I'll look into the android install.. good point about the better touchscreen support

**Comment by tijmenvangulik** [comment]
The other thing is that if you can use usb. This makes it more user friendly for the end user which does not have to do some actions to connect both devices. Your device will just directly work.
