### ISSUE TITLE
Online Regatta

### ISSUE THREAD

**Issue by bmillspaugh** [tijmenvangulik/Ergometerspace#5]
Sweet app Tijmen, thank you!  I was wondering if I can use this to hold an online regatta during corona quarantine?  If so, how many ergs can it handle?  I checked out a number of the widgets and it looks like the chat and the stop light will both be useful, but I didn't see a way to specify the length of the race (i.e. 2k)?  Also, I noticed that the data server is deprecated, but is it still possible to use it to connect up multiple ergs in on location (separated by at least 8 feet :-) and have them join the same race (private room) as other people on the internet who are connected individually?  Thanks again for creating this, and for any help you can provide in this unusual time where large indoor races are discouraged.

**Comment by tijmenvangulik** [comment]
Hi,

Cool that want to you organize this event. Ergometer-space takes the length of the race of the performance monitor (PM3-5). So if you want to race 2k every one should set it’s ergometer to 2k (if some one uses a different length , it is directly visible in race widget). The data server is deprecated but it should still be possible to use the data server. But there is also an alternative. When you open the pc/mac app you can select the  specific device in the options so you can assign for every app a different ergometer. (close all the widgets which you do not need to improve the performance) I have no experience with multiple ergometer since I own only one ergometer. In theory it should be able many ergometers, but there is only one way of knowing for sure is to test it. If you have any trouble or you have test results, let me know , may be I can fix it or optimize it. 

Tijmen

**Comment by tijmenvangulik** [comment]
In Italy they have done a ergometer race today with ergometer-space:

https://www.facebook.com/Canottaggio1888/videos/659821158163050/?t=4

I hope this gives you a bit inspiration:

TIjmen

**Comment by tijmenvangulik** [comment]
I have now added a feature which allows you to row in teams and you also have the observer role. This is ideal for rowing an regatta

**Comment by bmillspaugh** [comment]
> I have now added a feature which allows you to row in teams and you also have the observer role. This is ideal for rowing an regatta

That’s great to hear, thank you!  We will try it out and see how it works.  The challenge for us right now is that we are trying to line up practice races between our 200+ rowers and have found it a bit difficult to schedule & arrange things due to the ad-hoc nature of Ergometerspace (which makes it quick & easy to get started, but harder to manage a large group of people and multiple races).  We really appreciate the work you have done and don’t want to take away from that, so thank you for continuing to add functionality during this unprecedented time when everyone is trying to find a way to navigate social distancing in team sports.  Thanks again for all your help!
